
#  docker-compose Permette di creare multi-conteiner 
version: '3.8'

services:
# container 1
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports: "3306:3306"
      
    app:
    # container 2
      image: "app.py" # Sostituisci con l'immagine della tua applicazione
      restart: always
      depends_on: db
      ports:
        "5001:5001" # Modifica la porta in base alla tua applicazione
